### ISSUE TITLE
ActiveJob Support

### ISSUE THREAD

**Issue by piotrb** [payrollhero/dispatch-rider#50]
The idea is to bring full ActiveJob support to DR

Not entirely sure what this would look like .. 

There is a couple of distinct variants I suppose .. 

DR could be an ActiveJob provider where you create AJ jobs and dispatch them using DR, but that's not as useful .. 

The main thing to plan here would be what the transition for an app already using DR would look like, ideally it'd be good to maintain the message format to be the same when working with SQS.

The side motive here is to support AJ fully, this way DR and AJ would be interchangeable .. this would allow running DR via SQS in production, but for example resque in staging.

**Comment by more-ron** [comment]
Taking @fredbaa to check out this support.

**Comment by more-ron** [comment]
This is done: https://github.com/payrollhero/activejob-dispatch_rider
